spring:
  main:
    allow-circular-references: true
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: admin123!
    driver-class-name: org.postgresql.Driver
  data:
    #mongodb:
    #uri: ${MONGODB_URL}
    #database: ${MONGODB_DATABASE}
    #username: ${MONGODB_USERNAME} 
    #password: ${MONGODB_PASSWORD} 
    mongodb:
       uri: mongodb://localhost:27017/products_db
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    initialize-schema: always
  sql:
    init:
      mode: always
server:
  port: 9080
csv:
  file:
    filePath: C:/Users/User/Área de Trabalho/arquivos/producto.csv
    processedDir: C:/Users/User/Área de Trabalho/arquivos/Processado